### ISSUE TITLE
Is there going to be support for deprecation of Rearrangement's `rearrangement_id`?

### ISSUE THREAD

**Issue by Ross65536** [sfu-ireceptor/service-php-mongodb#207]
The ADC spec now currently defines for [Rearrangements](https://docs.airr-community.org/en/latest/datarep/rearrangements.html#rearrangementschema) that the `rearrangement_id` field is deprecated and that the `sequence_id` field is the new "main" id for rearrangements, given that the [spec](https://docs.airr-community.org/en/latest/api/adc_api.html) now specifies to use `sequence_id` in the `GET /v1/rearrangement/{sequence_id}` request.

Will this repository support this migration? 
Currently from the test data I have the `sequence_id` doesn't seem to have a suitable format for using as an ID (example value from a response I had `"SRR1298731.5421 H3UVCR001B41WD length=392"`)

**Comment by bcorrie** [comment]
@Ross65536 I believe we addressed this through email, correct? If not, 1000 apologies...

sequence_id should be returned as the correct, unique identifier for all ADC compatible repositories as of the AIRR v1.3 and the ADC API v1.0 releases. Let us know if you find that is not the case.

**Comment by Ross65536** [comment]
I think maybe your default `AIRR-iReceptorMapping.txt` CSV fields config file is not up to date in the docker image. I had to edit it myself to rename rearrangement IDs to sequence ID. Don't know if you have already updated this file.

**Comment by bcorrie** [comment]
Which branch of the iReceptor Turnkey are you using - and is this an experimental DB that you can reload the data for?

You should be using production-v3 for the ADC API version. If you are and is still isn't working, you may need to do a scripts/update_turnkey.sh. That should pull all of the correct docker containers which should have the correct mapping.

Since the AIRR v1.3 standard has some pretty significant improvements over the AIRR v1.2 standard, so if possible I would recommend on upgrading with a new data load - but of course that isn't practical for all...

If you have an old repository with data in it that you don't want to change, you can just tell docker to use the new ADC API docker container (let us know if that is what you would prefer). If we do that, then we will need to create a mapping to map any terms that don't match up with the AIRR v1.3 standard. This isn't too hard in most cases but depends on when you loaded the data.

Of course if you have any data in your repository that is valuable you might want to back it up before doing the update, although we find changing versions of the docker containers does not cause problems. The only question is how long ago did you load the data and with which version of the iReceptor Turnkey did you load it?

**Comment by bcorrie** [comment]
@Ross65536 I believe this is resolved, closing the issue - please reopen if we have missed something.
